import React from 'react';
import StudentDataProcessor from '@/components/StudentDataProcessor';
import { sourceData } from '@/data/sourceData';

const DataProcessor = () => {
  return <StudentDataProcessor sourceData={sourceData} />;
    "roster": [
      {"Email": "26tadami@student.nchstx.org", "First": "Thomas", "Last": "Adami", "Class": "ESS", "Period": "A"},
      {"Email": "26mcastillo@student.nchstx.org", "First": "Manuel", "Last": "Castillo", "Class": "ESS", "Period": "A"},
      {"Email": "26jdalton@student.nchstx.org", "First": "James", "Last": "Dalton", "Class": "ESS", "Period": "A"},
      {"Email": "26ademma@student.nchstx.org", "First": "Alana", "Last": "Demma", "Class": "ESS", "Period": "A"},
      {"Email": "26jfry@student.nchstx.org", "First": "Jon", "Last": "Fry", "Class": "ESS", "Period": "A"},
      {"Email": "26mgarcia1@student.nchstx.org", "First": "Moises", "Last": "Garcia", "Class": "ESS", "Period": "A"},
      {"Email": "26pholbert@student.nchstx.org", "First": "Payne", "Last": "Holbert", "Class": "ESS", "Period": "A"},
      {"Email": "26jirvin@student.nchstx.org", "First": "Jojo", "Last": "Irvin", "Class": "ESS", "Period": "A"},
      {"Email": "26djohnson@student.nchstx.org", "First": "Danny", "Last": "Johnson", "Class": "ESS", "Period": "A"},
      {"Email": "26dmunoz@student.nchstx.org", "First": "Destiny", "Last": "Munoz", "Class": "ESS", "Period": "A"},
      {"Email": "26jnguyen2@student.nchstx.org", "First": "Jaden", "Last": "Nguyen", "Class": "ESS", "Period": "A"},
      {"Email": "26corand@student.nchstx.org", "First": "Cooper", "Last": "Orand", "Class": "ESS", "Period": "A"},
      {"Email": "26rsalazar@student.nchstx.org", "First": "Ricky", "Last": "Salazar", "Class": "ESS", "Period": "A"},
      {"Email": "26jschuster@student.nchstx.org", "First": "Jackson", "Last": "Schuster", "Class": "ESS", "Period": "A"},
      {"Email": "26staylor@student.nchstx.org", "First": "Sophia", "Last": "Taylor", "Class": "ESS", "Period": "A"},
      {"Email": "26jtorres@student.nchstx.org", "First": "Jaden", "Last": "Torres", "Class": "ESS", "Period": "A"},
      {"Email": "26jvillegas@student.nchstx.org", "First": "Julyanna", "Last": "Villegas", "Class": "ESS", "Period": "A"},
      {"Email": "26bwalker@student.nchstx.org", "First": "Bailey", "Last": "Walker", "Class": "ESS", "Period": "A"},
      {"Email": "26kbutton@student.nchstx.org", "First": "Kate", "Last": "Button", "Class": "ECO", "Period": "C"},
      {"Email": "26dcantarella@student.nchstx.org", "First": "Danny", "Last": "Cantarella", "Class": "ECO", "Period": "C"},
      {"Email": "26eendres@student.nchstx.org", "First": "Elizabeth", "Last": "Endres", "Class": "ECO", "Period": "C"},
      {"Email": "26jfolzenlogen@student.nchstx.org", "First": "Josie", "Last": "Folzenlogen", "Class": "ECO", "Period": "C"},
      {"Email": "26mgarcia@student.nchstx.org", "First": "Mia", "Last": "Garcia", "Class": "ECO", "Period": "C"},
      {"Email": "26gkapend@student.nchstx.org", "First": "Gavrielle", "Last": "Kapend", "Class": "ECO", "Period": "C"},
      {"Email": "26nkoelzer@student.nchstx.org", "First": "Nick", "Last": "Koelzer", "Class": "ECO", "Period": "C"},
      {"Email": "26vle@student.nchstx.org", "First": "Vincent", "Last": "Le", "Class": "ECO", "Period": "C"},
      {"Email": "26bmock@student.nchstx.org", "First": "Bella", "Last": "Mock", "Class": "ECO", "Period": "C"},
      {"Email": "26cperales@student.nchstx.org", "First": "Claire", "Last": "Perales", "Class": "ECO", "Period": "C"},
      {"Email": "26pporras@student.nchstx.org", "First": "Philip", "Last": "Porras", "Class": "ECO", "Period": "C"},
      {"Email": "26preimer@student.nchstx.org", "First": "Paul", "Last": "Reimer", "Class": "ECO", "Period": "C"},
      {"Email": "26lrodriquez@student.nchstx.org", "First": "Lauren", "Last": "Rodriquez", "Class": "ECO", "Period": "C"},
      {"Email": "26sstavens@student.nchstx.org", "First": "Stellamae", "Last": "Stavens", "Class": "ECO", "Period": "C"},
      {"Email": "26ibarajas@student.nchstx.org", "First": "Isabella", "Last": "Barajas", "Class": "ESS", "Period": "D"},
      {"Email": "26jburgdorf@student.nchstx.org", "First": "Josie", "Last": "Burgdorf", "Class": "ESS", "Period": "D"},
      {"Email": "26scalzada@student.nchstx.org", "First": "Sebastian", "Last": "Calzada", "Class": "ESS", "Period": "D"},
      {"Email": "26xgarcia@student.nchstx.org", "First": "Xavier", "Last": "Garcia", "Class": "ESS", "Period": "D"},
      {"Email": "26lheidemann@student.nchstx.org", "First": "Luke", "Last": "Heidemann", "Class": "ESS", "Period": "D"},
      {"Email": "26pkennedy@student.nchstx.org", "First": "Preston", "Last": "Kennedy", "Class": "ESS", "Period": "D"},
      {"Email": "26mlataw@student.nchstx.org", "First": "Myu", "Last": "Lataw", "Class": "ESS", "Period": "D"},
      {"Email": "26gmacias@student.nchstx.org", "First": "German", "Last": "Macias", "Class": "ESS", "Period": "D"},
      {"Email": "26jmattox@student.nchstx.org", "First": "John David", "Last": "Mattox", "Class": "ESS", "Period": "D"},
      {"Email": "26lmcgrail@student.nchstx.org", "First": "Lauren", "Last": "McGrail", "Class": "ESS", "Period": "D"},
      {"Email": "26ipaltsev@student.nchstx.org", "First": "Ivana", "Last": "Paltsev", "Class": "ESS", "Period": "D"},
      {"Email": "26aperez@student.nchstx.org", "First": "Ashlynn", "Last": "Perez", "Class": "ESS", "Period": "D"},
      {"Email": "26mpior@student.nchstx.org", "First": "Marshall (Hayden)", "Last": "Pior", "Class": "ESS", "Period": "D"},
      {"Email": "26csanchez@student.nchstx.org", "First": "Camila", "Last": "Sanchez", "Class": "ESS", "Period": "D"},
      {"Email": "26ssholarsanderson@student.nchstx.org", "First": "Sidney", "Last": "Sholars-Anderson", "Class": "ESS", "Period": "D"},
      {"Email": "26twise@student.nchstx.org", "First": "Ty", "Last": "Wise", "Class": "ESS", "Period": "D"},
      {"Email": "26hzenk@student.nchstx.org", "First": "Hunter", "Last": "Zenk", "Class": "ESS", "Period": "D"},
      {"Email": "26mgillen@student.nchstx.org", "First": "Meg", "Last": "Gillen", "Class": "ECO", "Period": "G"},
      {"Email": "26sjackman@student.nchstx.org", "First": "Sam", "Last": "Jackman", "Class": "ECO", "Period": "G"},
      {"Email": "26omay@student.nchstx.org", "First": "Owen", "Last": "May", "Class": "ECO", "Period": "G"},
      {"Email": "26kmoore@student.nchstx.org", "First": "Keeley", "Last": "Moore", "Class": "ECO", "Period": "G"},
      {"Email": "26mmoore@student.nchstx.org", "First": "Mimi", "Last": "Moore", "Class": "ECO", "Period": "G"},
      {"Email": "26snajera@student.nchstx.org", "First": "Sara", "Last": "Najera", "Class": "ECO", "Period": "G"},
      {"Email": "26fpelzel@student.nchstx.org", "First": "Faith", "Last": "Pelzel", "Class": "ECO", "Period": "G"},
      {"Email": "26asalcedo@student.nchstx.org", "First": "Amanda", "Last": "Salcedo", "Class": "ECO", "Period": "G"},
      {"Email": "26aschmidt@student.nchstx.org", "First": "Avery", "Last": "Schmidt", "Class": "ECO", "Period": "G"},
      {"Email": "26sserna@student.nchstx.org", "First": "Sofia", "Last": "Serna", "Class": "ECO", "Period": "G"},
      {"Email": "26jsuter@student.nchstx.org", "First": "Jimmy", "Last": "Suter", "Class": "ECO", "Period": "G"},
      {"Email": "26nswigart@student.nchstx.org", "First": "Nick", "Last": "Swigart", "Class": "ECO", "Period": "G"},
      {"Email": "26atalabock@student.nchstx.org", "First": "Ava", "Last": "Talabock", "Class": "ECO", "Period": "G"},
      {"Email": "26jwerline@student.nchstx.org", "First": "Jake", "Last": "Werline", "Class": "ECO", "Period": "G"},
      {"Email": "26twilliams@student.nchstx.org", "First": "Tristan", "Last": "Williams", "Class": "ECO", "Period": "G"},
      {"Email": "26vbetancourt@student.nchstx.org", "First": "Valerie", "Last": "Betancourt", "Class": "ESS", "Period": "H"},
      {"Email": "26academartori@student.nchstx.org", "First": "Ann Marie", "Last": "Cademartori", "Class": "ESS", "Period": "H"},
      {"Email": "26adelsignore@student.nchstx.org", "First": "Antonio", "Last": "Del Signore", "Class": "ESS", "Period": "H"},
      {"Email": "26tdelatore@student.nchstx.org", "First": "Tyler", "Last": "Delatore", "Class": "ESS", "Period": "H"},
      {"Email": "26idurham@student.nchstx.org", "First": "Isabel", "Last": "Durham", "Class": "ESS", "Period": "H"},
      {"Email": "26jesparza@student.nchstx.org", "First": "Julian", "Last": "Esparza", "Class": "ESS", "Period": "H"},
      {"Email": "26agandara@student.nchstx.org", "First": "Andrew", "Last": "Gandara", "Class": "ESS", "Period": "H"},
      {"Email": "26agarcia@student.nchstx.org", "First": "Antonio", "Last": "Garcia", "Class": "ESS", "Period": "H"},
      {"Email": "26bhoang@student.nchstx.org", "First": "Brandon", "Last": "Hoang", "Class": "ESS", "Period": "H"},
      {"Email": "26oleuschner@student.nchstx.org", "First": "Olivia", "Last": "Leuschner", "Class": "ESS", "Period": "H"},
      {"Email": "26xmalone@student.nchstx.org", "First": "Xavier", "Last": "Malone", "Class": "ESS", "Period": "H"},
      {"Email": "26bmeche@student.nchstx.org", "First": "Brayden", "Last": "Meche", "Class": "ESS", "Period": "H"},
      {"Email": "26jramirez@student.nchstx.org", "First": "Jocelyn", "Last": "Ramirez", "Class": "ESS", "Period": "H"},
      {"Email": "26lsallee@student.nchstx.org", "First": "Lyrix", "Last": "Sallee", "Class": "ESS", "Period": "H"},
      {"Email": "26ksanchez@student.nchstx.org", "First": "Kassandra", "Last": "Sanchez", "Class": "ESS", "Period": "H"},
      {"Email": "26gspurgeon@student.nchstx.org", "First": "Gabe", "Last": "Spurgeon", "Class": "ESS", "Period": "H"},
      {"Email": "26cvu@student.nchstx.org", "First": "Clara", "Last": "Vu", "Class": "ESS", "Period": "H"},
      {"Email": "26ewheeler@student.nchstx.org", "First": "Ellorie", "Last": "Wheeler", "Class": "ESS", "Period": "H"}
    ],
    "student_report": [
      {"Student ID (System)": "16931", "First Name": "Olivia", "Last Name": "Leuschner", "Middle Name": "Clare", "Grade Level": "12", "User Name": "26OLeuschner"},
      {"Student ID (System)": "16946", "First Name": "Lauren", "Last Name": "Rodriquez", "Middle Name": "Raquel", "Grade Level": "12", "User Name": "26LRodriquez"},
      {"Student ID (System)": "16949", "First Name": "Jon", "Last Name": "Fry", "Middle Name": "Drake", "Grade Level": "12", "User Name": "26JFry"},
      {"Student ID (System)": "16961", "First Name": "Thomas", "Last Name": "Adami", "Middle Name": "Gilbert", "Grade Level": "12", "User Name": "26TAdami"},
      {"Student ID (System)": "16962", "First Name": "Ava", "Last Name": "Talabock", "Middle Name": "", "Grade Level": "12", "User Name": "26ATalabock"},
      {"Student ID (System)": "16966", "First Name": "Sophia", "Last Name": "Taylor", "Middle Name": "Ann", "Grade Level": "12", "User Name": "26STaylor"},
      {"Student ID (System)": "16975", "First Name": "Manuel", "Last Name": "Castillo", "Middle Name": "Alberto", "Grade Level": "12", "User Name": "26MCastillo"},
      {"Student ID (System)": "16976", "First Name": "Julian", "Last Name": "Esparza", "Middle Name": "", "Grade Level": "12", "User Name": "26JEsparza"},
      {"Student ID (System)": "16982", "First Name": "Phillip", "Last Name": "Porras", "Middle Name": "", "Grade Level": "12", "User Name": "26PPorras"},
      {"Student ID (System)": "16999", "First Name": "Samuel", "Last Name": "Jackman", "Middle Name": "Francis", "Grade Level": "12", "User Name": "26SJackman"},
      {"Student ID (System)": "17004", "First Name": "Nicholas", "Last Name": "Koelzer", "Middle Name": "Helmuth", "Grade Level": "12", "User Name": "26NKoelzer"},
      {"Student ID (System)": "17005", "First Name": "Cooper", "Last Name": "Orand", "Middle Name": "Daniel Martinez", "Grade Level": "12", "User Name": "26COrand"},
      {"Student ID (System)": "17017", "First Name": "Payne", "Last Name": "Holbert", "Middle Name": "Martin", "Grade Level": "12", "User Name": "26PHolbert"},
      {"Student ID (System)": "17037", "First Name": "Antonio", "Last Name": "Garcia", "Middle Name": "Manuel", "Grade Level": "12", "User Name": "26AGarcia"},
      {"Student ID (System)": "17049", "First Name": "Bailey", "Last Name": "Walker", "Middle Name": "Rae", "Grade Level": "12", "User Name": "26BWalker"},
      {"Student ID (System)": "17055", "First Name": "Marshall", "Last Name": "Pior", "Middle Name": "Hayden", "Grade Level": "12", "User Name": "26MPior"},
      {"Student ID (System)": "17064", "First Name": "Gavrielle", "Last Name": "Kapend", "Middle Name": "", "Grade Level": "12", "User Name": "26GKapend"},
      {"Student ID (System)": "17078", "First Name": "Amanda", "Last Name": "Salcedo", "Middle Name": "Rose Angela", "Grade Level": "12", "User Name": "26ASalcedo"},
      {"Student ID (System)": "17080", "First Name": "Sofia", "Last Name": "Serna", "Middle Name": "Mia", "Grade Level": "12", "User Name": "26SSerna"},
      {"Student ID (System)": "17085", "First Name": "Alana", "Last Name": "Demma", "Middle Name": "Anh", "Grade Level": "12", "User Name": "26ADemma"},
      {"Student ID (System)": "17094", "First Name": "Jocelyn", "Last Name": "Ramirez", "Middle Name": "", "Grade Level": "12", "User Name": "26JRamirez"},
      {"Student ID (System)": "17097", "First Name": "Jackson", "Last Name": "Schuster", "Middle Name": "", "Grade Level": "12", "User Name": "26JSchuster"},
      {"Student ID (System)": "17103", "First Name": "Josie", "Last Name": "Burgdorf", "Middle Name": "Ellen", "Grade Level": "12", "User Name": "26JBurgdorf"},
      {"Student ID (System)": "17116", "First Name": "Sara", "Last Name": "Najera", "Middle Name": "Elizabeth", "Grade Level": "12", "User Name": "26SNajera"},
      {"Student ID (System)": "17122", "First Name": "Kassandra", "Last Name": "Sanchez", "Middle Name": "Dariela", "Grade Level": "12", "User Name": "26KSanchez"},
      {"Student ID (System)": "17127", "First Name": "Myu Sut Jat", "Last Name": "Lataw", "Middle Name": "", "Grade Level": "12", "User Name": "26MLataw"},
      {"Student ID (System)": "17131", "First Name": "German", "Last Name": "Macias", "Middle Name": "", "Grade Level": "12", "User Name": "26GMacias"},
      {"Student ID (System)": "17138", "First Name": "Daniel", "Last Name": "Cantarella", "Middle Name": "Christopher", "Grade Level": "12", "User Name": "26DCantarella"},
      {"Student ID (System)": "17141", "First Name": "Destiny", "Last Name": "Munoz", "Middle Name": "Zaude", "Grade Level": "12", "User Name": "26DMunoz"},
      {"Student ID (System)": "17146", "First Name": "Andrew", "Last Name": "Gandara", "Middle Name": "", "Grade Level": "12", "User Name": "26AGandara"},
      {"Student ID (System)": "17149", "First Name": "Ricardo", "Last Name": "Salazar", "Middle Name": "", "Grade Level": "12", "User Name": "26RSalazar"},
      {"Student ID (System)": "17153", "First Name": "Preston", "Last Name": "Kennedy", "Middle Name": "Cade", "Grade Level": "12", "User Name": "26PKennedy"},
      {"Student ID (System)": "17158", "First Name": "Nicholas", "Last Name": "Swigart", "Middle Name": "James", "Grade Level": "12", "User Name": "26NSwigart"},
      {"Student ID (System)": "17161", "First Name": "Tristan", "Last Name": "Williams", "Middle Name": "James", "Grade Level": "12", "User Name": "26TWilliams"},
      {"Student ID (System)": "17164", "First Name": "Marie", "Last Name": "Gillen", "Middle Name": "E", "Grade Level": "12", "User Name": "26MGillen"},
      {"Student ID (System)": "17168", "First Name": "Vincent", "Last Name": "Le", "Middle Name": "Can", "Grade Level": "12", "User Name": "26VLe"},
      {"Student ID (System)": "17170", "First Name": "Xavier", "Last Name": "Garcia", "Middle Name": "Thomas", "Grade Level": "12", "User Name": "26XGarcia"},
      {"Student ID (System)": "17178", "First Name": "Camila", "Last Name": "Sanchez", "Middle Name": "", "Grade Level": "12", "User Name": "26CSanchez"},
      {"Student ID (System)": "17180", "First Name": "Josephine", "Last Name": "Folzenlogen", "Middle Name": "Marie", "Grade Level": "12", "User Name": "26JFolzenlogen"},
      {"Student ID (System)": "17184", "First Name": "Tyler", "Last Name": "Delatore", "Middle Name": "Paul", "Grade Level": "12", "User Name": "26TDelatore"},
      {"Student ID (System)": "17189", "First Name": "Avery", "Last Name": "Schmidt", "Middle Name": "Maria", "Grade Level": "12", "User Name": "26ASchmidt"},
      {"Student ID (System)": "17190", "First Name": "Bella", "Last Name": "Mock", "Middle Name": "", "Grade Level": "12", "User Name": "26BMock"},
      {"Student ID (System)": "17193", "First Name": "Daniel", "Last Name": "Johnson", "Middle Name": "David", "Grade Level": "12", "User Name": "26DJohnson"},
      {"Student ID (System)": "17195", "First Name": "Ivana", "Last Name": "Paltsev", "Middle Name": "Sofia", "Grade Level": "12", "User Name": "26IPaltsev"},
      {"Student ID (System)": "17203", "First Name": "Gabriel", "Last Name": "Spurgeon", "Middle Name": "Steven", "Grade Level": "12", "User Name": "26GSpurgeon"},
      {"Student ID (System)": "17204", "First Name": "Valerie", "Last Name": "Betancourt", "Middle Name": "N", "Grade Level": "12", "User Name": "26VBetancourt"},
      {"Student ID (System)": "17207", "First Name": "Julyanna", "Last Name": "Villegas", "Middle Name": "", "Grade Level": "12", "User Name": "26JVillegas"},
      {"Student ID (System)": "17210", "First Name": "Owen", "Last Name": "May", "Middle Name": "Case", "Grade Level": "12", "User Name": "26OMay"},
      {"Student ID (System)": "17214", "First Name": "Moises", "Last Name": "Garcia", "Middle Name": "", "Grade Level": "12", "User Name": "26MGarcia1"},
      {"Student ID (System)": "17217", "First Name": "Isabel", "Last Name": "Durham", "Middle Name": "", "Grade Level": "12", "User Name": "26IDurham"},
      {"Student ID (System)": "17226", "First Name": "Stellamae", "Last Name": "Stavens", "Middle Name": "An", "Grade Level": "12", "User Name": "26SStavens"},
      {"Student ID (System)": "17242", "First Name": "Xavier", "Last Name": "Malone", "Middle Name": "Michael", "Grade Level": "12", "User Name": "26XMalone"},
      {"Student ID (System)": "17245", "First Name": "Lauren", "Last Name": "McGrail", "Middle Name": "Cassidy", "Grade Level": "12", "User Name": "26LMcGrail"},
      {"Student ID (System)": "17258", "First Name": "Paul", "Last Name": "Reimer", "Middle Name": "Edward", "Grade Level": "12", "User Name": "26PReimer"},
      {"Student ID (System)": "17267", "First Name": "James", "Last Name": "Suter", "Middle Name": "Robert", "Grade Level": "12", "User Name": "26JSuter"},
      {"Student ID (System)": "17282", "First Name": "Claire", "Last Name": "Perales", "Middle Name": "Marie", "Grade Level": "12", "User Name": "26CPerales"},
      {"Student ID (System)": "17286", "First Name": "Jaden", "Last Name": "Torres", "Middle Name": "Anthony", "Grade Level": "12", "User Name": "26JTorres"},
      {"Student ID (System)": "17293", "First Name": "Tyler", "Last Name": "Wise", "Middle Name": "Conrado", "Grade Level": "12", "User Name": "26TWise"},
      {"Student ID (System)": "17296", "First Name": "Kate", "Last Name": "Button", "Middle Name": "Elizabeth", "Grade Level": "12", "User Name": "26KButton"},
      {"Student ID (System)": "17300", "First Name": "Faith", "Last Name": "Pelzel", "Middle Name": "Yvonne Elizabeth", "Grade Level": "12", "User Name": "26FPelzel"},
      {"Student ID (System)": "17304", "First Name": "Sebastian", "Last Name": "Calzada", "Middle Name": "", "Grade Level": "12", "User Name": "26SCalzada"},
      {"Student ID (System)": "17305", "First Name": "Ashlynn", "Last Name": "Perez", "Middle Name": "Briana", "Grade Level": "12", "User Name": "26APerez"},
      {"Student ID (System)": "17313", "First Name": "Mia", "Last Name": "Garcia", "Middle Name": "", "Grade Level": "12", "User Name": "26MGarcia"},
      {"Student ID (System)": "17319", "First Name": "John", "Last Name": "Zenk", "Middle Name": "Hunter", "Grade Level": "12", "User Name": "26JZenk"},
      {"Student ID (System)": "17323", "First Name": "Clara", "Last Name": "Vu", "Middle Name": "Q", "Grade Level": "12", "User Name": "26CVu"},
      {"Student ID (System)": "17334", "First Name": "Keeley", "Last Name": "Moore", "Middle Name": "Anne", "Grade Level": "12", "User Name": "26KMoore"},
      {"Student ID (System)": "17337", "First Name": "Mimi", "Last Name": "Moore", "Middle Name": "Jane", "Grade Level": "12", "User Name": "26MMoore"},
      {"Student ID (System)": "17342", "First Name": "Elizabeth", "Last Name": "Endres", "Middle Name": "", "Grade Level": "12", "User Name": "26EEndres"},
      {"Student ID (System)": "17349", "First Name": "Ellorie", "Last Name": "Wheeler", "Middle Name": "Laura", "Grade Level": "12", "User Name": "26EWheeler"},
      {"Student ID (System)": "17355", "First Name": "Brandon", "Last Name": "Hoang", "Middle Name": "Khoa", "Grade Level": "12", "User Name": "26BHoang"},
      {"Student ID (System)": "17370", "First Name": "Ann Marie", "Last Name": "Cademartori", "Middle Name": "Christine", "Grade Level": "12", "User Name": "26ACademartori"},
      {"Student ID (System)": "17383", "First Name": "Sidney", "Last Name": "Sholars-Anderson", "Middle Name": "Anthony", "Grade Level": "12", "User Name": "26SSholarsAnderson"},
      {"Student ID (System)": "17388", "First Name": "Antonio", "Last Name": "Del Signore", "Middle Name": "Rocco", "Grade Level": "12", "User Name": "26ADelSignore"},
      {"Student ID (System)": "17397", "First Name": "Jaden M", "Last Name": "Nguyen", "Middle Name": "MinhTri", "Grade Level": "12", "User Name": "26JNguyen2"},
      {"Student ID (System)": "17398", "First Name": "Brayden", "Last Name": "Meche", "Middle Name": "Allen", "Grade Level": "12", "User Name": "26BMeche"},
      {"Student ID (System)": "17402", "First Name": "Jake", "Last Name": "Werline", "Middle Name": "Davis", "Grade Level": "12", "User Name": "26JWerline"},
      {"Student ID (System)": "17629", "First Name": "Luke", "Last Name": "Heidemann", "Middle Name": "S", "Grade Level": "12", "User Name": "26LHeidemann"},
      {"Student ID (System)": "17701", "First Name": "James", "Last Name": "Dalton", "Middle Name": "Dixon", "Grade Level": "12", "User Name": "26JDalton"},
      {"Student ID (System)": "18384", "First Name": "Lyrix", "Last Name": "Sallee", "Middle Name": "Loveil", "Grade Level": "12", "User Name": "26lsallee@student.nchstx.org"},
      {"Student ID (System)": "18395", "First Name": "John David", "Last Name": "Mattox", "Middle Name": "Tobias", "Grade Level": "12", "User Name": "26JMattox"},
      {"Student ID (System)": "19054", "First Name": "Joseph", "Last Name": "Irvin", "Middle Name": "Paul", "Grade Level": "12", "User Name": "26jirvin"},
      {"Student ID (System)": "16986", "First Name": "Jade", "Last Name": "Barajas", "Middle Name": "Isabella", "Grade Level": "12", "User Name": "26jbarajas"}
    ],
    "current_students": [
      {"id": "0625a930-337d-4b42-9399-fffa0ea83ea0", "first_name": "Gavrielle", "last_name": "Kapend", "sis_id": "17064"},
      {"id": "0809c1e8-d5a0-4bf3-b94b-007ef0cb9197", "first_name": "Ivana", "last_name": "Paltsev", "sis_id": "17195"}
      // ... truncated for brevity, but would include all data
    ]
  };

  return <StudentDataProcessor sourceData={sourceData} />;
};

export default DataProcessor;