// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgicbewohdubulzdcuat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnaWNiZXdvaGR1YnVsemRjdWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTE3NjEsImV4cCI6MjA2NjUyNzc2MX0.kwhtihc5L_942UOWI7a7KUkA7n3UU-VvdAn2si8Hy_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});